const products = [
    { id: 1, name: "Hair Scrunchie", price: 39, category: "Accessories" },
    { id: 2, name: "Hair Clips Set", price: 49, category: "Accessories" },
    { id: 3, name: "Claw Clip Large", price: 79, category: "Accessories" },
    { id: 4, name: "Mobile Cover Basic", price: 249, category: "Accessories" },
    { id: 5, name: "Women's Wallet", price: 399, category: "Accessories" },
    { id: 6, name: "Women Belt", price: 299, category: "Accessories" },
    { id: 7, name: "Fashion Sunglasses", price: 499, category: "Accessories" },
    { id: 8, name: "Oxidised Earrings", price: 129, category: "Imitation Jewellery" },
    { id: 9, name: "Jhumkas Pair", price: 159, category: "Imitation Jewellery" },
    { id: 10, name: "Kundan Necklace Set", price: 349, category: "Imitation Jewellery" },
    { id: 11, name: "Daily Wear Chain", price: 149, category: "Imitation Jewellery" },
    { id: 12, name: "Bracelet Fashion", price: 129, category: "Imitation Jewellery" },
    { id: 13, name: "Lipstick Value", price: 199, category: "Makeup" },
    { id: 14, name: "Liquid Matte Lipstick", price: 349, category: "Makeup" },
    { id: 15, name: "Compact Powder", price: 249, category: "Makeup" },
    { id: 16, name: "Foundation Mass", price: 349, category: "Makeup" },
    { id: 17, name: "Kajal Basic", price: 180, category: "Makeup" },
    { id: 18, name: "Kajal Premium", price: 315, category: "Makeup" },
    { id: 19, name: "Mascara Value", price: 299, category: "Makeup" },
    { id: 20, name: "Nail Paint Basic", price: 69, category: "Makeup" },
    { id: 21, name: "Nail Paint Premium", price: 149, category: "Makeup" },
    { id: 22, name: "Face Wash Basic", price: 149, category: "Skincare" },
    { id: 23, name: "Face Wash Premium", price: 259, category: "Skincare" },
    { id: 24, name: "Moisturizer Basic", price: 159, category: "Skincare" },
    { id: 25, name: "Moisturizer Premium", price: 349, category: "Skincare" },
    { id: 26, name: "Sunscreen Basic", price: 249, category: "Skincare" },
    { id: 27, name: "Sunscreen Premium", price: 399, category: "Skincare" },
    { id: 28, name: "Serum Vit C", price: 299, category: "Skincare" },
    { id: 29, name: "Serum Niacinamide", price: 449, category: "Skincare" },
    { id: 30, name: "Sheet Mask Single", price: 59, category: "Skincare" },
    { id: 31, name: "Shampoo Basic", price: 149, category: "Haircare" },
    { id: 32, name: "Shampoo Premium", price: 299, category: "Haircare" },
    { id: 33, name: "Conditioner Basic", price: 169, category: "Haircare" },
    { id: 34, name: "Conditioner Premium", price: 299, category: "Haircare" },
    { id: 35, name: "Hair Oil Basic", price: 129, category: "Haircare" },
    { id: 36, name: "Hair Oil Premium", price: 249, category: "Haircare" },
    { id: 37, name: "Hair Serum Basic", price: 249, category: "Haircare" },
    { id: 38, name: "Hair Serum Premium", price: 399, category: "Haircare" },
    { id: 39, name: "Cotton Leggings Basic", price: 299, category: "Private Label" },
    { id: 40, name: "Cotton Leggings Premium", price: 399, category: "Private Label" },
    { id: 41, name: "Jeggings Basic", price: 499, category: "Private Label" },
    { id: 42, name: "Jeggings Premium", price: 799, category: "Private Label" },
    { id: 43, name: "Cotton Top Basic", price: 349, category: "Private Label" },
    { id: 44, name: "Cotton Top Premium", price: 499, category: "Private Label" },
    { id: 45, name: "Long Tunic", price: 499, category: "Private Label" },
    { id: 46, name: "Casual Top Basic", price: 399, category: "Women Fashion" },
    { id: 47, name: "Casual Top Premium", price: 799, category: "Women Fashion" },
    { id: 48, name: "Casual Dress Basic", price: 699, category: "Women Fashion" },
    { id: 49, name: "Casual Dress Premium", price: 1199, category: "Women Fashion" },
    { id: 50, name: "Jeans Basic", price: 699, category: "Women Fashion" },
    { id: 51, name: "Jeans Premium", price: 1499, category: "Women Fashion" },
    { id: 52, name: "Palazzo Basic", price: 349, category: "Women Fashion" },
    { id: 53, name: "Palazzo Premium", price: 699, category: "Women Fashion" },
    { id: 54, name: "Kurti Basic", price: 399, category: "Ethnic Wear" },
    { id: 55, name: "Kurti Premium", price: 799, category: "Ethnic Wear" },
    { id: 56, name: "Kurti Set Basic", price: 899, category: "Ethnic Wear" },
    { id: 57, name: "Kurti Set Premium", price: 1699, category: "Ethnic Wear" },
    { id: 58, name: "Dupatta Basic", price: 149, category: "Ethnic Wear" },
    { id: 59, name: "Dupatta Premium", price: 349, category: "Ethnic Wear" },
    { id: 60, name: "T-shirt Basic", price: 349, category: "Men Fashion" },
    { id: 61, name: "T-shirt Premium", price: 499, category: "Men Fashion" },
    { id: 62, name: "Casual Shirt Basic", price: 499, category: "Men Fashion" },
    { id: 63, name: "Casual Shirt Premium", price: 799, category: "Men Fashion" },
    { id: 64, name: "Joggers Basic", price: 499, category: "Men Fashion" },
    { id: 65, name: "Joggers Premium", price: 899, category: "Men Fashion" },
    { id: 66, name: "Men Wallet", price: 299, category: "Men Fashion" },
    { id: 67, name: "Makeup Sponge", price: 149, category: "Beauty Tools" },
    { id: 68, name: "Tweezers Basic", price: 99, category: "Beauty Tools" },
    { id: 69, name: "Tweezers Premium", price: 199, category: "Beauty Tools" },
    { id: 70, name: "Compact Mirror", price: 99, category: "Beauty Tools" },
    { id: 71, name: "Travel Bottle Set", price: 199, category: "Beauty Tools" },
    { id: 72, name: "Gift Hamper Basic", price: 499, category: "Seasonal" },
    { id: 73, name: "Gift Hamper Premium", price: 999, category: "Seasonal" },
    { id: 74, name: "Rain Poncho Basic", price: 299, category: "Seasonal" },
    { id: 75, name: "Rain Poncho Premium", price: 499, category: "Seasonal" },
    { id: 76, name: "Winter Beanie", price: 249, category: "Seasonal" },
    { id: 77, name: "Winter Gloves", price: 199, category: "Seasonal" }
];

products.forEach(product => {
    let filename = product.name.replace(/ /g, '_');
    product.image = `assets/images/${filename}.jpg`;
});